### ISSUE TITLE
Service provider won't register

### ISSUE THREAD

**Issue by leopinzon** [thepinecode/impersonate#1]
Hi guys, before anything else, congrats and thanks a lot for taking the time to develop this awesome package. 

I am experiencing issues on the package's configuration. The problem is on the configuration file creation, I am getting the following message:

```
$ php artisan vendor:publish --provider=Pine\Impersonate\ImpersonateServiceProvider
                                 
  [BadMethodCallException]       
  Method prefix does not exist.
```  

I opened the `Pine\Impersonate\ImpersonateServiceProvider.php` to check what could be happening and found an error within the code on this `if` declaration statement: 

```
// Register the custom blade directive's opening tag
Blade::if('impersonate', function () {
     return session()->has('original_user');
});
```

The error says: 
```Expected: variable or identifier or { or dollar```

I am using Laravel 5.3 and PHP 7.1. 

Thanks a lot!
Best

**Comment by iamgergo** [comment]
@leopinzon Hi, thank you and thanks for your issue.

The custom `if` blade directives are part of the framework since `5.5` (see: https://laravel-news.com/bladeif).

Probably that could be the problem. I'll update the docs regarding the min. required version.

Thank you again!

**Comment by leopinzon** [comment]
Sure! happy to help. Anyway, is there a version that works with my Laravel version? 
Thanks a lot

**Comment by iamgergo** [comment]
Yes, that's the only solution. Okay, I'll update the repository and make a new release.
Soon I'll let you know.

Thanks!

**Comment by leopinzon** [comment]
Actually I forked and did it myself.... but... there are other problems to make it compatible with Laravel 5.3: 

* Blada directives (Already fixed)
* Routing has a newer standard (Already fixed)
* Dispatchable trait was launched on Laravel 5.4 (Stucked on this one, looking for a workaround)

I will continue with this last one, all ideas are welcomed!

**Comment by iamgergo** [comment]
@leopinzon I merged your PR, thank you!

I made a new release, please check if it works well for you as well!
